### ISSUE TITLE
[Request] Player progress sharing, and multiple players using the same table.

### ISSUE THREAD

**Issue by vizthex123** [ZengineeringTeam/ResearchTable#45] opened 2020-10-13 17:15 UTC
* Minecraft Version: 1.12.2
 * Mod Version: 0.9.5

Title. My friend and I made a server, but progress wasn't shared and I had to make my own table.
Do you think you could address this in the next update or one soon after?

Thanks.

**Comment by Snownee** [comment] 2020-10-13 17:22
Yes it's planned, and I will implement it soon. But I am too busy recently (see my github activities). Maybe few days later, idk. sorry

**Comment by Snownee** [comment] 2020-10-13 17:22
Duplicate of #37

**Closed as completed by Snownee** 2020-10-13 17:22 UTC

**Comment by vizthex123** [comment] 2020-10-13 22:44
Well, if it's planned that's fine. Sorry for the duplicate issue.

And if you're able to make multiple players use the same table (instead of each one having to make their own) that'd be great too.
